config/routes.rb
Rails.application.routes.draw do

  resources :invoices
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  devise_for :users, skip: :all

  root "invoices#index"

  resources :invoices

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  before_save :downcase_fields, :calculate_invoice_fees

def self.search(search)
  if search
    where(["first_name LIKE ?", "%#{search}%"])
  else
    all
  end
end

  def calculate_invoice_fees
  invoice_tax = self.cost * 0.07
  self.tax = invoice_tax
  self.fees = (self.cost + invoice_tax) * 0.0349 + 0.49
  self.net = self.cost - self.fees
  end

  def downcase_fields
    self.first_name.downcase!
    self.last_name.downcase!
  end

end

app/models/user.rb
class User < ApplicationRecord
 has_many :invoices
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_user!

    helper_method :user_signed_in?, :current_user, :user_session


    def after_sign_in_path_for(resource)
      root_path
    end
      
    def after_sign_out_path_for(resource)
      root_path
    end
    
    def index
    end
   
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    # @invoices = Invoice.all
    @invoices = Invoice.search(params[:search])
end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])

  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:email, :description, :cost, :tax, :fees, :net, :stripe, :paypal, :first_name, :last_name, :revamp, :website, :seo, :webmail, :user_id, :search)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper  

    def admin
        user_signed_in? && current_user.id == 1
    end
    
end

app/helpers/invoices_helper.rb
module InvoicesHelper

end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :website, "Web Design" %>
    <%= form.check_box :website %>
    <%= form.label :revamp, "Revamp" %>
    <%= form.check_box :revamp %>
    <%= form.label :seo, "SEO Improvement" %>
    <%= form.check_box :seo %>
    <%= form.label :webmail, "Email Blast" %>
    <%= form.check_box :webmail %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.text_field :tax %>
  </div>

  <div class="field">
    <%= form.radio_button :stripe, "Stripe" %>
    <%= form.label :stripe, "Stripe" %>
    <%= form.radio_button :paypal, "PayPal" %>
    <%= form.label :paypal, "PayPal" %>
  </div>

  <div class="field">
    <%= form.label :fees %>
    <%= form.text_field :fees %>
  </div>

  <div class="field">
    <%= form.label :net %>
    <%= form.text_field :net %>
  </div>

  <%= form.hidden_field :user_id , :value => current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Invoices</h1>

<%= render 'shared/search' %>
<%= render 'shared/invoicemenu' %>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<div class="container w-100 d-flex justify-content-center border border-dark border-1 rounded-3 print">

  <div class="grid">
    <h1 class="g-col-12">Payment Invoice</h1>

    <p class="g-col-12 text-right"> 
      <%= @invoice.first_name %> <%= @invoice.last_name %>
    </p>

    <p class="g-col-12 text-right">
    <%= @invoice.email %>
    </p>

    <h4 class="g-col-12 text-center">Service Description</h4>
    <p class="g-col-12 text-left"><strong>Description: </strong><%= @invoice.description %></p>

    <h4 class="g-col-12 text-center">Purchase Items</h4>

    <div class="g-col-12 text-left">
      <p><strong>Website: </strong><%= @invoice.website %></p>
    

      <p><strong>Revamp:</strong> <%= @invoice.revamp %></p>
    
      <p><strong>SEO:</strong> <%= @invoice.seo %></p>
      
      <p><strong>Webmail:</strong> <%= @invoice.webmail %></p>
    <div>

    <h4 class="g-col-12 text-center">Billing Information</h4>

    <div class="g-col-12 text-right">
      <p><strong>Cost:</strong> <%= number_to_currency(@invoice.cost) %></p>
      <p><strong>Tax:</strong> <%= number_to_currency(@invoice.tax) %></p>
      <p><strong>Stripe:</strong> <%= @invoice.stripe %></p>
      <p><strong>PayPal:</strong> <%= @invoice.paypal %></p>
      <p><strong>Fees:</strong> <%= number_to_currency(@invoice.fees) %></p>
      <p><strong>Net:</strong> <%= number_to_currency(@invoice.net) %></p>
      <p><strong>User:</strong> <%= @invoice.user_id %></p>
    </div>

  </div>
</div>

<div>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> | <%= link_to 'Destroy', invoice_path(@invoice), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', invoices_path %> <p onclick="window.print()">Print this invoice</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sale</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

  </head>

  <body>
  <%= render 'shared/menu' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>



    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>

  </body>
</html>

app/views/shared/_invoicemenu.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="invoice-tab" data-bs-toggle="tab" data-bs-target="#invoice" type="button" role="tab" aria-controls="home" aria-selected="true">Invoices</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Profile</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="messages-tab" data-bs-toggle="tab" data-bs-target="#messages" type="button" role="tab" aria-controls="messages" aria-selected="false">Messages</button>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="invoice" role="tabpanel" aria-labelledby="home-tab">
    <%= render 'shared/invoicetable' %>
  </div>
  <div class="tab-pane" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
  <div class="tab-pane" id="messages" role="tabpanel" aria-labelledby="messages-tab">...</div>
</div>

<script>
  var firstTabEl = document.querySelector('#myTab li:last-child button')
  var firstTab = new bootstrap.Tab(firstTabEl)

  firstTab.show()
</script>

app/views/shared/_invoicetable.html.erb
<table class="table">
<thead>
  <tr>
    <th scope="col">Invoice #</th>
    <th scope="col">First Name</th>
    <th scope="col">Last Name</th>
    <th scope="col">Email</th>
    <th scope="col">Website</th>
    <th scope="col">Revamp</th>
    <th scope="col">SEO</th>
    <th scope="col">Webmail</th>
    <th scope="col">Description</th>
    <th scope="col">Cost</th>
    <th scope="col">Tax</th>
    <th scope="col">Stripe</th>
    <th scope="col">Paypal</th>
    <th scope="col">Fees</th>
    <th scope="col">Net</th>
  </tr>
</thead>

<tbody>

  <% @invoices.each do |invoice| %>
    <% if current_user.id == invoice.user_id || admin %>
    <tr>
      <th scope="row"><%= link_to invoice.id, invoice %></th>
      <td><%= invoice.first_name %></td>
      <td><%= invoice.last_name %></td>
      <td><%= invoice.email %></td>

      <td>
      <% if invoice.website == true %>
      <%= invoice.website %>
      <% end %>
      </td>

      <td>
      <% if invoice.revamp == true %>
      <%= invoice.revamp %>
      <% end %>
      </td>

      <td>
      <% if invoice.seo == true %>
      <%= invoice.seo %>
      <% end %>
      </td>

      <td>
      <% if invoice.webmail == true %>
      <%= invoice.webmail %>
      <% end %>
      </td>

      <td><%= invoice.description %></td>
      <td><%= number_to_currency(invoice.cost) %></td>
      <td><%= number_to_currency(invoice.tax) %></td>
      
      <td>
      <% if invoice.stripe == true %>
      <%= invoice.stripe %>
      <% end %>
      </td>
      
      <td>
      <% if invoice.paypal == true %>
      <%= invoice.paypal %>
      <% end %>
      </td>

      <td><%= number_to_currency(invoice.fees) %></td>
      <td><%= number_to_currency(invoice.net) %></td>
    </tr>
    <% end %>
  <% end %>
</tbody>
</table>
<br>

app/views/shared/_menu.html.erb
  <% if current_user %>

  <span class="navbar-text">
  <%= "Logged in as #{current_user.email}" %> <%= link_to 'Log Out', destroy_user_session_path, method: :delete %> 
  <% else %>
  <%= link_to 'Log In', new_user_session_path %> or <%= link_to 'Sign Up', new_user_registration_path %>
  </span>
  <% end %>

  <%= link_to 'Invoices', invoices_path %>

app/views/shared/_search.html.erb
<%= form_with(url: '/invoices', method: 'get', local: true) do %>
    <%= label_tag(:search, "Search by first name:") %>
    <%= text_field_tag(:search) %>
    <%= submit_tag("search") %>
    <% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>